### ISSUE TITLE
README.md Installation Markdown

### ISSUE THREAD

**Issue by Nates-World21** [WmeDiscord/Lucord#1]
The HTML Markdown in ``README.md`` is a tad broken on [Lucord Website](https://lucord.wmeluna.com)!

<h2> Preview </h2>
<img src="https://user-images.githubusercontent.com/103780769/185823128-a135c4c4-5d6a-4c6d-a8a9-e3c1db8e8155.png">

**Comment by WmeLuna** [comment]
Added markdown.js to apply markdown wherever Jekyll didn't.
